export const GET_PARTY_CONNECTION_PROGRESS = "GET_PARTY_CONNECTION_PROGRESS";
export const GET_PARTY_CONNECTION_SUCCESS = "GET_PARTY_CONNECTION_SUCCESS";
export const GET_PARTY_CONNECTION_ERROR = "GET_PARTY_CONNECTION_ERROR";

export const POST_PARTY_CONNECTION_PROGRESS = "POST_PARTY_CONNECTION_PROGRESS";
export const POST_PARTY_CONNECTION_SUCCESS = "POST_PARTY_CONNECTION_SUCCESS";
export const POST_PARTY_CONNECTION_ERROR = "POST_PARTY_CONNECTION_ERROR";

export const DELETE_PARTY_CONNECTION_PROGRESS = "DELETE_PARTY_CONNECTION_PROGRESS";
export const DELETE_PARTY_CONNECTION_SUCCESS = "DELETE_PARTY_CONNECTION_SUCCESS";
export const DELETE_PARTY_CONNECTION_ERROR = "DELETE_PARTY_CONNECTION_ERROR";